name: Laravel Tests with PEST

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: laravel
          POSTGRES_USER: laravel
          POSTGRES_PASSWORD: secret
        ports:
          - 5432:5432
        options: --health-cmd="pg_isready" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, xml, curl, dom, fileinfo, pgsql, pdo, pdo_pgsql
        coverage: none

    - name: Copy .env
      run: |
        cd src
        cp .env.example .env

    - name: Install dependencies
      run: |
        cd src
        composer install --prefer-dist --no-progress --no-interaction

    - name: Generate application key
      run: |
        cd src
        php artisan key:generate

    - name: Configure PostgreSQL
      run: |
        cd src
        echo "DB_CONNECTION=pgsql" >> .env
        echo "DB_HOST=127.0.0.1" >> .env
        echo "DB_PORT=5432" >> .env
        echo "DB_DATABASE=laravel" >> .env
        echo "DB_USERNAME=laravel" >> .env
        echo "DB_PASSWORD=secret" >> .env

    - name: Run migrations
      run: |
        cd src
        php artisan migrate --force

    - name: Execute tests
      run: |
        cd src
        ./vendor/bin/pest