name: Laravel Tests with PEST

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Copy .env
      run: |
        cd src
        cp .env.example .env

    - name: Start Docker containers
      run: docker-compose up -d db

    - name: Wait for database
      run: sleep 5

    - name: Install dependencies with Docker
      run: docker-compose run --rm app composer install --prefer-dist --no-progress --no-interaction

    - name: Generate application key
      run: docker-compose run --rm app php artisan key:generate

    - name: Run migrations
      run: docker-compose run --rm app php artisan migrate --force

    - name: Execute tests
      run: docker-compose run --rm test